com

diff --git a/kubernetes-manifests/lowmem/loadgenerator.yaml b/kubernetes-manifests/lowmem/loadgenerator.yaml
--- a/kubernetes-manifests/lowmem/loadgenerator.yaml
+++ b/kubernetes-manifests/lowmem/loadgenerator.yaml
@@ -36,49 +36,51 @@ spec:
         runAsNonRoot: true
         runAsUser: 1000
       initContainers:
-      - command:
-        - /bin/sh
-        - -exc
-        - |
-          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
-          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
-          if test $STATUSCODE -ne 200; then
-              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
-              exit 1
-          fi
-        name: frontend-check
-        securityContext:
-          allowPrivilegeEscalation: false
-          capabilities:
-            drop:
-              - all
-          privileged: false
-          readOnlyRootFilesystem: true
-        image: busybox:latest
-        imagePullPolicy: IfNotPresent
-        env:
-        - name: FRONTEND_ADDR
-          value: "frontend:8081"
+        - command:
+            - /bin/sh
+            - -exc
+            - |
+              echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
+              STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+              if test $STATUSCODE -ne 200; then
+                  echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+                  exit 1
+              fi
+          name: frontend-check
+          securityContext:
+            allowPrivilegeEscalation: false
+            capabilities:
+              drop:
+                - all
+            privileged: false
+            readOnlyRootFilesystem: true
+          image: busybox:latest
+          imagePullPolicy: IfNotPresent
+          env:
+            - name: FRONTEND_ADDR
+              value: "frontend:8081"
       containers:
-      - name: loadgenerator
-        securityContext:
-          allowPrivilegeEscalation: false
-          capabilities:
-            drop:
-              - all
-          privileged: false
-          readOnlyRootFilesystem: true
-        image: dpacheconr/loadgenerator
-        imagePullPolicy: IfNotPresent
-        env:
-        - name: FRONTEND_ADDR
-          value: "frontend:8081"
-        - name: USERS
-          value: "10"
-        resources:
-          requests:
-            cpu: 10m
-            memory: 70Mi
-          limits:
-            cpu: 15m
-            memory: 100Mi
+        - name: loadgenerator
+          securityContext:
+            allowPrivilegeEscalation: false
+            capabilities:
+              drop:
+                - all
+            privileged: false
+            readOnlyRootFilesystem: true
+          image: {{REPO}}/loadgenerator
+          imagePullPolicy: IfNotPresent
+          env:
+            - name: FRONTEND_ADDR
+              value: "frontend:8081"
+            - name: USERS
+              value: "10"
+          resources:
+            requests:
+              cpu: 10m
+              memory: 70Mi
+            limits:
+              cpu: 15m
+              memory: 100Mi
+      
+
